/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {
    button: Button;
    carousel: Carousel;
    'contact-form': ContactForm;
    gallery: Gallery;
    headline: Headline;
    'status-alert': StatusAlert;
    text: Text;
    section: Section;
    realizations: Realizations;
  };
  collections: {
    pages: Page;
    media: Media;
    users: User;
    dialogs: Dialog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    dialogs: DialogsSelect<false> | DialogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
    downloads: Download;
    navigation: Navigation;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    downloads: DownloadsSelect<false> | DownloadsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "button".
 */
export interface Button {
  label: string;
  type: 'page' | 'custom' | 'dialog' | 'file';
  page?: (number | null) | Page;
  file?: (number | null) | Media;
  url?: string | null;
  /**
   * If set, pressing the button will open the selected dialog.
   */
  dialog?: (number | null) | Dialog;
  id?: string | null;
  blockName?: string | null;
  blockType: 'button';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  keywords?: string | null;
  description?: string | null;
  content?:
  | (
    | {
      /**
       * Allows to create a links to the section
       */
      slug?: string | null;
      children?:
      | (
        | {
          label: string;
          type: 'page' | 'custom' | 'dialog' | 'file';
          page?: (number | null) | Page;
          file?: (number | null) | Media;
          url?: string | null;
          /**
           * If set, pressing the button will open the selected dialog.
           */
          dialog?: (number | null) | Dialog;
          id?: string | null;
          blockName?: string | null;
          blockType: 'button';
        }
        | {
          text?: string | null;
          images?: (number | Media)[] | null;
          id?: string | null;
          blockName?: string | null;
          blockType: 'carousel';
        }
        | {
          lines: {
            text: string;
            id?: string | null;
          }[];
          id?: string | null;
          blockName?: string | null;
          blockType: 'headline';
        }
        | {
          color: string;
          content: string;
          id?: string | null;
          blockName?: string | null;
          blockType: 'status-alert';
        }
        | {
          variant?: ('p1' | 'p2' | 'p3') | null;
          text?: string | null;
          id?: string | null;
          blockName?: string | null;
          blockType: 'text';
        }
        | {
          id?: string | null;
          blockName?: string | null;
          blockType: 'contact-form';
        }
        | {
          title?: string | null;
          items?:
          | {
            images: (number | Media)[];
            title: string;
            category: 'kilns' | 'controllers' | 'accessories' | 'other';
            /**
             * e.g. '$100', 'from $50'
             */
            price?: string | null;
            description?: string | null;
            id?: string | null;
          }[]
          | null;
          id?: string | null;
          blockName?: string | null;
          blockType: 'gallery';
        }
        | {
          triggerLabel: string;
          slides?:
          | {
            image: number | Media;
            description?: string | null;
            id?: string | null;
          }[]
          | null;
          id?: string | null;
          blockName?: string | null;
          blockType: 'realizations';
        }
      )[]
      | null;
      id?: string | null;
      blockName?: string | null;
      blockType: 'section';
    }
    | {
      triggerLabel: string;
      slides?:
      | {
        image: number | Media;
        description?: string | null;
        id?: string | null;
      }[]
      | null;
      id?: string | null;
      blockName?: string | null;
      blockType: 'realizations';
    }
  )[]
  | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dialogs".
 */
export interface Dialog {
  id: number;
  title?: string | null;
  description?: string | null;
  content?:
  | {
    id?: string | null;
    blockName?: string | null;
    blockType: 'contact-form';
  }[]
  | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carousel".
 */
export interface Carousel {
  text?: string | null;
  images?: (number | Media)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'carousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-form".
 */
export interface ContactForm {
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact-form';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  title?: string | null;
  items?:
  | {
    images: (number | Media)[];
    title: string;
    category: 'kilns' | 'controllers' | 'accessories' | 'other';
    /**
     * e.g. '$100', 'from $50'
     */
    price?: string | null;
    description?: string | null;
    id?: string | null;
  }[]
  | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "headline".
 */
export interface Headline {
  lines: {
    text: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'headline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "status-alert".
 */
export interface StatusAlert {
  color: string;
  content: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'status-alert';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "text".
 */
export interface Text {
  variant?: ('p1' | 'p2' | 'p3') | null;
  text?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'text';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "section".
 */
export interface Section {
  /**
   * Allows to create a links to the section
   */
  slug?: string | null;
  children?:
  | (
    | {
      label: string;
      type: 'page' | 'custom' | 'dialog' | 'file';
      page?: (number | null) | Page;
      file?: (number | null) | Media;
      url?: string | null;
      /**
       * If set, pressing the button will open the selected dialog.
       */
      dialog?: (number | null) | Dialog;
      id?: string | null;
      blockName?: string | null;
      blockType: 'button';
    }
    | {
      text?: string | null;
      images?: (number | Media)[] | null;
      id?: string | null;
      blockName?: string | null;
      blockType: 'carousel';
    }
    | {
      lines: {
        text: string;
        id?: string | null;
      }[];
      id?: string | null;
      blockName?: string | null;
      blockType: 'headline';
    }
    | {
      color: string;
      content: string;
      id?: string | null;
      blockName?: string | null;
      blockType: 'status-alert';
    }
    | {
      variant?: ('p1' | 'p2' | 'p3') | null;
      text?: string | null;
      id?: string | null;
      blockName?: string | null;
      blockType: 'text';
    }
    | {
      id?: string | null;
      blockName?: string | null;
      blockType: 'contact-form';
    }
    | {
      title?: string | null;
      items?:
      | {
        images: (number | Media)[];
        title: string;
        category: 'kilns' | 'controllers' | 'accessories' | 'other';
        /**
         * e.g. '$100', 'from $50'
         */
        price?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
      | null;
      id?: string | null;
      blockName?: string | null;
      blockType: 'gallery';
    }
    | {
      triggerLabel: string;
      slides?:
      | {
        image: number | Media;
        description?: string | null;
        id?: string | null;
      }[]
      | null;
      id?: string | null;
      blockName?: string | null;
      blockType: 'realizations';
    }
  )[]
  | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'section';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "realizations".
 */
export interface Realizations {
  triggerLabel: string;
  slides?:
  | {
    image: number | Media;
    description?: string | null;
    id?: string | null;
  }[]
  | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'realizations';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
  | {
    id: string;
    createdAt?: string | null;
    expiresAt: string;
  }[]
  | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
  | {
    [k: string]: unknown;
  }
  | unknown[]
  | string
  | number
  | boolean
  | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
  | ({
    relationTo: 'pages';
    value: number | Page;
  } | null)
  | ({
    relationTo: 'media';
    value: number | Media;
  } | null)
  | ({
    relationTo: 'users';
    value: number | User;
  } | null)
  | ({
    relationTo: 'dialogs';
    value: number | Dialog;
  } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
  | {
    [k: string]: unknown;
  }
  | unknown[]
  | string
  | number
  | boolean
  | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  keywords?: T;
  description?: T;
  content?:
  | T
  | {
    section?:
    | T
    | {
      slug?: T;
      children?:
      | T
      | {
        button?:
        | T
        | {
          label?: T;
          type?: T;
          page?: T;
          file?: T;
          url?: T;
          dialog?: T;
          id?: T;
          blockName?: T;
        };
        carousel?:
        | T
        | {
          text?: T;
          images?: T;
          id?: T;
          blockName?: T;
        };
        headline?:
        | T
        | {
          lines?:
          | T
          | {
            text?: T;
            id?: T;
          };
          id?: T;
          blockName?: T;
        };
        'status-alert'?:
        | T
        | {
          color?: T;
          content?: T;
          id?: T;
          blockName?: T;
        };
        text?:
        | T
        | {
          variant?: T;
          text?: T;
          id?: T;
          blockName?: T;
        };
        'contact-form'?:
        | T
        | {
          id?: T;
          blockName?: T;
        };
        gallery?:
        | T
        | {
          title?: T;
          items?:
          | T
          | {
            images?: T;
            title?: T;
            category?: T;
            price?: T;
            description?: T;
            id?: T;
          };
          id?: T;
          blockName?: T;
        };
        realizations?:
        | T
        | {
          triggerLabel?: T;
          slides?:
          | T
          | {
            image?: T;
            description?: T;
            id?: T;
          };
          id?: T;
          blockName?: T;
        };
      };
      id?: T;
      blockName?: T;
    };
    realizations?:
    | T
    | {
      triggerLabel?: T;
      slides?:
      | T
      | {
        image?: T;
        description?: T;
        id?: T;
      };
      id?: T;
      blockName?: T;
    };
  };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
  | T
  | {
    thumbnail?:
    | T
    | {
      url?: T;
      width?: T;
      height?: T;
      mimeType?: T;
      filesize?: T;
      filename?: T;
    };
    card?:
    | T
    | {
      url?: T;
      width?: T;
      height?: T;
      mimeType?: T;
      filesize?: T;
      filename?: T;
    };
    large?:
    | T
    | {
      url?: T;
      width?: T;
      height?: T;
      mimeType?: T;
      filesize?: T;
      filename?: T;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
  | T
  | {
    id?: T;
    createdAt?: T;
    expiresAt?: T;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dialogs_select".
 */
export interface DialogsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  content?:
  | T
  | {
    'contact-form'?:
    | T
    | {
      id?: T;
      blockName?: T;
    };
  };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * Email settings
   */
  email: {
    /**
     * SMTP server address
     */
    host: string;
    /**
     * SMTP server port
     */
    port: number;
    /**
     * SMTP server username
     */
    username: string;
    /**
     * SMTP server password
     */
    password: string;
    /**
     * Sender email address
     */
    sender: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "downloads".
 */
export interface Download {
  id: number;
  categories?:
  | {
    title: string;
    files?:
    | {
      name: string;
      file: number | Media;
      id?: string | null;
    }[]
    | null;
    id?: string | null;
  }[]
  | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  whyUsLabel?: string | null;
  missionLabel?: string | null;
  worksLabel?: string | null;
  servicesLabel?: string | null;
  contactLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  email?:
  | T
  | {
    host?: T;
    port?: T;
    username?: T;
    password?: T;
    sender?: T;
  };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "downloads_select".
 */
export interface DownloadsSelect<T extends boolean = true> {
  categories?:
  | T
  | {
    title?: T;
    files?:
    | T
    | {
      name?: T;
      file?: T;
      id?: T;
    };
    id?: T;
  };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  whyUsLabel?: T;
  missionLabel?: T;
  worksLabel?: T;
  servicesLabel?: T;
  contactLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config { }
}